feat: Multi AZ RDS Cluster Support
terraform-aws-modules/terraform-aws-rds pull request #424
Opened 2022-08-01 13:40 UTC by magreenbaum

## Description
Support for multi-az rds clusters (mysql and postgres). 
Added in aws provider version 4.6: https://github.com/hashicorp/terraform-provider-aws/pull/23684

Additional comments: 
There are a lot of limitations on non-aurora rds clusters at the moment. Only attributes that are supported for non-aurora rds clusters are included in this PR. Aurora RDS cluster module referenced for this feature: https://github.com/terraform-aws-modules/terraform-aws-rds-aurora

Refs: 
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/create-multi-az-db-cluster.html
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/multi-az-db-clusters-concepts.html

## Motivation and Context
https://github.com/terraform-aws-modules/terraform-aws-rds/issues/408

## Breaking Changes
No.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [x] I have executed `pre-commit run -a` on my pull request

2022-08-01 14:31 UTC, bryantbiggs requested changes
I'm not sure I understand whats going on in this PR 
- `aws_rds_cluster` is an Aurora cluster and we have a separate module for that
- I don't think we need to add the KMS key module and multi-region to each example, nor do I understand how it relates to multi-AZ cluster support

2022-08-01 14:46 UTC, magreenbaum commented
> 

The terraform-aws-provider recently added support for non-aurora engines (mysql & postgres). Ref: https://github.com/hashicorp/terraform-provider-aws/pull/23684
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/create-multi-az-db-cluster.html
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/multi-az-db-clusters-concepts.html
I think using the aurora module would work (some attributes would need to be added) but the naming is a bit confusing. If someone is looking to create a non-aurora mysql rds multi-az cluster for example, looking here might make more sense.

KMS key module was added to the cross-region-replica-postgres example due to an error:
<img width="1348" alt="Screen Shot 2022-07-30 at 10 53 55 PM" src="https://user-images.githubusercontent.com/69476188/182174864-7dd42f3d-6e7f-462a-8466-2e3a0e0a0373.png">
A KMS key in the destination region must be specified when the source DB is encrypted. 
I can remove this from the PR and make it a separate fix if that is preferable. 

I added examples for both multi-az cluster supported engine types but I can remove one since we don't need both.

2022-08-08 17:49 UTC, bryantbiggs commented
hmm, I'm not sure how best to proceed. It seems silly to replicate [aws_rds_cluster](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/main.tf#L47) here just to support multi-AZ RDS, plus that now opens the door for other cluster resources which just exacerbates the situation. 

I'm more inclined to just show an example of how to use the Aurora module to create a multi-AZ RDS cluster (non-Aurora). @antonbabenko what are your thoughts?

2022-08-08 19:52 UTC, antonbabenko commented
I agree with @bryantbiggs. There is already a separate module and if necessary (looks like it is a case) let's update just an example in this one.

If something is missing in another RDS module we have, please open a small PR there.

2022-08-08 20:17 UTC, magreenbaum commented
Understood, that makes sense, thanks for the feedback @bryantbiggs @antonbabenko.

2022-08-08 20:17 UTC, closed without merging